//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class arduBase
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public decimal Temp { get; set; }
        public short PwrWarn { get; set; }
    }
}
