//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElectronMeta
    {
        public int ID { get; set; }
        public string coreid { get; set; }
        public short active { get; set; }
        public int predicament { get; set; }
        public string name { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public Nullable<decimal> altitude { get; set; }
    }
}
