//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPredicament
    {
        public int ID { get; set; }
        public short active { get; set; }
        public short type { get; set; }
        public int label { get; set; }
        public string shortDescription { get; set; }
        public string comment { get; set; }
    }
}
