//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeather
    {
        public long ID { get; set; }
        public string @event { get; set; }
        public string coreid { get; set; }
        public System.DateTime publishedAt { get; set; }
        public string prtclUserid { get; set; }
        public Nullable<short> prtclFwVersion { get; set; }
        public decimal temperature { get; set; }
        public decimal humidity { get; set; }
        public decimal pressure { get; set; }
        public decimal rainMM { get; set; }
        public decimal windKPH { get; set; }
        public decimal gustKPH { get; set; }
        public decimal windDirection { get; set; }
        public decimal powerStatus { get; set; }
    }
}
